# Generated by Django 6.0.6 on 2026-07-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mydummy',
            options={'ordering': ['id']},
        ),
    ]
