# Generated by Django 6.0.4 on 2026-08-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
