# Generated by Django 6.0.6 on 2026-08-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0003_alter_invoice_created_by_alter_invoice_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.inventory'),
        ),
    ]
