# Generated by Django 6.0.6 on 2026-08-25 18:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_warehouses(apps, schema_editor):
    FulfillmentWarehouse = apps.get_model("fulfillment", "Warehouse")
    InventoryWarehouse = apps.get_model("inventory", "Warehouse")
    Shipment = apps.get_model("fulfillment", "Shipment")

    for old_warehouse in FulfillmentWarehouse.objects.all().iterator():
        new_warehouse = InventoryWarehouse.objects.create(
            name=old_warehouse.name,
            location=old_warehouse.location,
            contact_number=old_warehouse.contact_number,
            status=old_warehouse.status,
            is_deleted=old_warehouse.is_deleted,
            deleted_at=old_warehouse.deleted_at,
        )
        Shipment.objects.filter(warehouse_id=old_warehouse.pk).update(
            warehouse_id=new_warehouse.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0003_alter_exchange_created_by_alter_exchange_updated_by_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_warehouses,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='inventory.warehouse'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
