# Generated by Django 6.0.4 on 2026-08-27 03:53

import products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_created_by_alter_brand_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='Stores lists, labels, details, summary, and table data.', validators=[products.models.product.validate_document_structure]),
        ),
    ]
