# Generated by Django 6.0.4 on 2026-08-27 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_dues_created_by_alter_dues_updated_by'),
        ('inventory', '0001_initial'),
        ('users', '0009_employee_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse facility associated with this financial obligation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dues', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='dues',
            index=models.Index(fields=['warehouse', 'status'], name='finance_due_warehou_99de33_idx'),
        ),
    ]
