# Generated by Django 6.0.6 on 2026-08-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_address_default_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_default_address_per_customer_type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='address_type',
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('ShippingExecutive', 'Shipping Executive'), ('InventoryManager', 'Inventory Manager'), ('SupportAgent', 'Support Agent')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer', 'address_type'), name='unique_default_address_per_customer_type'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_user_id'),
        ),
    ]
