# Generated by Django 6.0.4 on 2026-08-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
