# Generated by Django 6.0.4 on 2026-08-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0008_alter_address_created_by_alter_address_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where this employee is stationed (required for inventory managers & shipping executives).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='inventory.warehouse'),
        ),
    ]
